#!/usr/bin/env python3
"""embed.py — encrypt assets and emit resources_generated.cpp

Reads assets/ (prompt-ctf-scoring.md, skills/, tamper_rules.txt),
XOR-encrypts each with a per-resource pseudo-random key,
emits src/resources_generated.cpp with the cipher + key tables.

Usage: python embed.py [assets_dir] [output_cpp]
"""
import os
import sys
import json

DEFAULT_ASSETS = os.path.join(os.path.dirname(__file__), '..', 'assets')
DEFAULT_OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'resources_generated.cpp')

# Deterministic key derivation (seeded) — NOT cryptographic, just anti-glance.
# Real deployment: derive from machine fingerprint at runtime.
KEY_SEED = 0x5A5A


def xorkey(seed: int, length: int) -> bytes:
    key = bytearray()
    x = seed
    for _ in range(length):
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        key.append((x >> 16) & 0xFF)
    return bytes(key)


def encrypt(data: bytes, seed: int) -> tuple[bytes, bytes]:
    key = xorkey(seed, len(data))
    out = bytes(b ^ k for b, k in zip(data, key))
    return out, key


def c_array(name: str, data: bytes) -> str:
    if not data:
        return f'extern const unsigned char {name}[] = {{0}};\nextern const size_t {name}Len = 0;\n'
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append('    ' + ', '.join(f'0x{b:02X}' for b in chunk) + ',')
    body = '\n'.join(rows).rstrip(',')
    return f'extern const unsigned char {name}[] = {{\n{body}\n}};\nextern const size_t {name}Len = {len(data)};\n'


def main():
    assets = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ASSETS)
    out_cpp = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT)

    # Load assets
    def read(name):
        p = os.path.join(assets, name)
        if not os.path.exists(p):
            return b''
        with open(p, 'rb') as f:
            return f.read()

    agents = read('prompt-ctf-scoring.md')
    agents_v45 = read('prompt-sandbox-executor.md')
    agents_deepseek = read('prompt-deepseek优化版.md')
    rules = read('tamper_rules.txt')
    dashboard = read('dashboard.html')
    qa_json = read('qa.json')
    rewrite_prompt = read('rewrite_prompt.txt')
    rewriter_builtin = read('rewriter_builtin.json')
    if not rewriter_builtin:
        # Optional provider credentials must never be required for a clean build.
        # Keep a valid disabled config so the local-rule fallback remains usable.
        rewriter_builtin = b'{\n  "enabled": false,\n  "provider": "",\n  "model": "",\n  "timeout_sec": 30,\n  "use_proxy": false\n}\n'
        print('  rewriter_builtin.json: missing -> embedded disabled defaults')

    # Normalize CRLF -> LF for embedded assets (git autocrlf may have
    # converted working-tree files; embedded bytes must be stable so
    # verify's content match is deterministic across checkouts).
    def norm(b):
        return b.replace(b'\r\n', b'\n')

    agents = norm(agents)
    agents_v45 = norm(agents_v45)
    agents_deepseek = norm(agents_deepseek)
    rules = norm(rules)
    dashboard = norm(dashboard)
    rewrite_prompt = norm(rewrite_prompt)
    rewriter_builtin = norm(rewriter_builtin)

    # Skills index: name -> (cipher, key, len) ; content encrypted per-skill
    skills_dir = os.path.join(assets, 'skills')
    skill_names = []
    skill_blobs = []  # (name, cipher_bytes)
    if os.path.isdir(skills_dir):
        for entry in sorted(os.listdir(skills_dir)):
            skill_md = os.path.join(skills_dir, entry, 'SKILL.md')
            if os.path.isfile(skill_md):
                with open(skill_md, 'rb') as f:
                    content = f.read()
                seed = KEY_SEED + len(skill_names) + 1
                cipher, key = encrypt(content, seed)
                skill_names.append(entry)
                skill_blobs.append((entry, cipher, key))

    # Emit
    lines = []
    lines.append('// AUTO-GENERATED by tools/embed.py — do not edit')
    lines.append('#include <cstddef>')
    lines.append('')
    lines.append('namespace helmx {')
    lines.append('')

    def emit_var(name, data, seed):
        cipher, key = encrypt(data, seed)
        lines.append(c_array(name + 'Cipher', cipher))
        lines.append(c_array(name + 'Key', key))
        lines.append('')

    emit_var('kAgentsMd', agents, KEY_SEED)
    emit_var('kAgentsV45', agents_v45, KEY_SEED + 0x5000)
    emit_var('kAgentsDeepseek', agents_deepseek, KEY_SEED + 0x8000)
    emit_var('kTamperRules', rules, KEY_SEED + 0x1000)
    emit_var('kDashboardHtml', dashboard, KEY_SEED + 0x3000)
    emit_var('kQaJson', qa_json, KEY_SEED + 0x7000)
    emit_var('kRewritePrompt', rewrite_prompt, KEY_SEED + 0x4000)
    emit_var('kRewriterBuiltin', rewriter_builtin, KEY_SEED + 0x6000)

    # skills index: names array
    lines.append('extern const char* const kSkillNames[] = {')
    for n in skill_names:
        lines.append(f'    "{n}",')
    lines.append('};')
    lines.append(f'extern const size_t kSkillCount = {len(skill_names)};')
    lines.append('')

    # per-skill cipher/key
    for idx, (name, cipher, key) in enumerate(skill_blobs):
        safe = 'kSkill' + str(idx)
        name_bytes = name.encode('utf-8')
        lines.append(f'extern const char {safe}Name[] = {{')
        lines.append('    ' + ', '.join(f"'{c}'" for c in name) + ", '\\0',")
        lines.append('};')
        lines.append(f'extern const size_t {safe}NameLen = {len(name_bytes)};')
        lines.append(c_array(safe + 'Cipher', cipher))
        lines.append(c_array(safe + 'Key', key))
        lines.append('')

    # lookup table
    lines.append('struct SkillEntry { const char* name; const unsigned char* cipher; size_t cipher_len; const unsigned char* key; size_t key_len; };')
    lines.append('extern const SkillEntry kSkills[] = {')
    for idx, (name, cipher, key) in enumerate(skill_blobs):
        lines.append(f'    {{ kSkill{idx}Name, kSkill{idx}Cipher, kSkill{idx}CipherLen, kSkill{idx}Key, kSkill{idx}KeyLen }},')
    lines.append('};')
    lines.append('')
    lines.append('}  // namespace helmx')
    lines.append('')

    os.makedirs(os.path.dirname(out_cpp), exist_ok=True)
    with open(out_cpp, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print(f'embed.py: assets={assets}')
    print(f'  prompt-ctf-scoring.md: {len(agents)} bytes -> cipher')
    print(f'  prompt-deepseek优化版.md: {len(agents_deepseek)} bytes -> cipher')
    print(f'  tamper_rules: {len(rules)} bytes -> cipher')
    print(f'  skills: {len(skill_blobs)} embedded')
    print(f'  -> {out_cpp}')


if __name__ == '__main__':
    main()
